WIP: E2e test of uncommon namespace
mondoohq/mondoo-operator pull request #202
Opened 2022-03-21 14:56 UTC by jensgrnb

Signed-off-by: jensgrnb <jens.grunborg@endocode.com>

closes #169

2022-03-23 14:20 UTC, jensgrnb commented
This can be reviewed

2022-03-31 07:10 UTC, chris-rock commented
Can we rebase this to latest main?

2022-03-31 08:22 UTC, jensgrnb commented
Rebased

2022-03-31 11:10 UTC, chris-rock requested changes
Thank you @jensgrnb I added some smaller change requests

2022-03-31 11:10 UTC, chris-rock commented on .github/workflows/e2e.yaml
> +          kubectl delete -f config/samples/k8s_v1alpha1_mondooauditconfig.yaml
That should be a separate step. It is confusing to package that under the undeploy task. I recommend adding a step after undeploy that starts a new deploy and undeploy for the namespace specific test

2022-03-31 11:10 UTC, chris-rock commented on config/rbac/kustomization.yaml
> +- service_account_workloads.yaml
why are we changing this?

2022-03-31 20:29 UTC, joelddiaz commented on .github/workflows/e2e.yaml
> +          kubectl create secret generic mondoo-client --namespace not-mondoo-operator --from-file=config=creds.json
Add the `rm creds.json` step that was removed above here, or just keep the creds creation/cleanup all together around the `kubectl create secret` command.

2022-03-31 20:29 UTC, joelddiaz commented on .github/workflows/e2e.yaml
> +          kubectl apply -f config/samples/k8s_v1alpha1_mondooauditconfig.yaml
You can just do this in a single line
```suggestion
          yq '.metadata.namespace= "not-mondoo-operator"' config/samples/k8s_v1alpha1_mondooauditconfig.yaml | kubectl apply -
```

2022-03-31 20:29 UTC, joelddiaz commented on test/deployment-policy-uncommon-ns.yaml
> +    query: k8s.deployments.one( name == "mondoo-operator-controller-manager" && namespace == "mondoo-operator" )
These two queries don't seem to be significant for the non-default-namespace test as this is already covered for the standard namespace test.

2022-04-01 15:53 UTC, joelddiaz commented
@chris-rock I added a commit to address the pieces I found during review yesterday. Also while filling in some missing pieces, I found that some changes to the MondooAuditConfig (like the workloads.serviceAccount field) weren't causing an update to the Deployment, so the checking for when the Deployment needs an update has been re-worked.

This should be good for a review now.

2022-04-04 18:24 UTC, chris-rock approved these changes
@joelddiaz Thank you for adding the changes. This looks great now. Lets update the delete kubectl command and we are ready to go

2022-04-04 18:24 UTC, chris-rock commented on .github/workflows/e2e.yaml
> +          kubectl create secret generic mondoo-client --namespace not-mondoo-operator --from-file=config=creds.json
To avoid copy paste issues going forward, I would just always doing the complete round. Adding a secret is not an expensive task

2022-04-04 18:24 UTC, chris-rock commented on .github/workflows/e2e.yaml
>            kubectl delete -f config/samples/k8s_v1alpha1_mondooauditconfig.yaml
Yes lets do this

2022-04-04 20:24 UTC, joelddiaz commented
> @joelddiaz Thank you for adding the changes. This looks great now. Lets update the delete kubectl command and we are ready to go

@chris-rock What changes are you saying that should be made to the delete command(s)?

2022-04-04 20:29 UTC, joelddiaz commented
> You recommended to make the delete command more specific [#202 (comment)](https://github.com/mondoohq/mondoo-operator/pull/202#discussion_r839996292)

Ah yes, I did implement that in one of my commits https://github.com/mondoohq/mondoo-operator/pull/202/files#diff-a2de7550554c0198ac7f959c78a19ee0996921c98034411de47a7dd49b0c209bR77-R78

W/o the kubectl delete of the MondooAuditConfig the `make undeploy` would hang, so I was forced to add it to get through a complete E2E.

2022-04-04 20:31 UTC, chris-rock commented
Ah I was missing the line under the comment. Thank you

2022-04-04 20:32 UTC, merged