⭐️ add scanner client
mondoohq/mondoo-operator pull request #270
Opened 2022-04-12 09:28 UTC by chris-rock

add a simple http client for the mondoo scanner

2022-04-12 10:00 UTC, imilchev requested changes

2022-04-12 10:01 UTC, imilchev commented on pkg/scanner/scanner.go
> +	"github.com/pkg/errors"
perhaps it's good to check if we have this dependency in any of the other projects as well

2022-04-12 10:11 UTC, chris-rock commented on pkg/scanner/scanner.go
> +	"github.com/pkg/errors"
yeah, we can remove that, that was an auto-import

2022-04-12 10:13 UTC, chris-rock commented on pkg/scanner/scanner.go
> +func (s *Scanner) HealthCheck(ctx context.Context, in *HealthCheckRequest) (*HealthCheckResponse, error) {
This is standard protobuf rpc style

2022-04-12 10:13 UTC, chris-rock commented on pkg/scanner/scanner.go
> +	url := s.Endpoint + "/Health/Check"
that will not work if you want to talk to multiple clients where the url may be different

2022-04-12 10:15 UTC, chris-rock commented on pkg/scanner/scanner.go
> +type HealthCheckRequest struct{}
Going forward this is going to be auto-generated. I just used the GRPC service style, see https://grpc.io/docs/languages/go/basics/

2022-04-12 10:15 UTC, chris-rock commented on pkg/scanner/scanner_test.go
> +	data, err := ioutil.ReadFile("./testdata/webhook-payload.json")
great idea

2022-04-12 10:16 UTC, chris-rock commented on pkg/scanner/scanner.go
> +	req, err := http.NewRequest("POST", url, reader)
+1

2022-04-12 10:17 UTC, imilchev commented on pkg/scanner/scanner.go
> +type HealthCheckRequest struct{}
I was unaware it's going to be a gRPC interface

2022-04-12 10:29 UTC, imilchev commented on pkg/scanner/scanner.go
> +	url := s.Endpoint + "/Health/Check"
I meant storing just `/Health/Check` part as a const. You also mock that in the tests and can reference that const. In case that value changes, at least you update it in `scanner.go` and the tests will work as well. Otherwise, we would have to update it in 2 places

2022-04-12 20:58 UTC, chris-rock commented
Thank you for the improvements @joelddiaz, I cannot self-approve, so you have to approve :-)

2022-04-13 14:33 UTC, imilchev commented on pkg/scanner/scanner_test.go
> +	data, err := ioutil.ReadFile("./testdata/webhook-payload.json")
if this branch gets rebased on `main`, it will be possible to fix this

2022-04-13 16:36 UTC, joelddiaz commented on pkg/scanner/scanner_test.go
> +	data, err := ioutil.ReadFile("./testdata/webhook-payload.json")
I ended up just using the `embed` functionality since the filename with the example payload is static.

2022-04-13 17:59 UTC, joelddiaz commented
@imilchev this should be good for a review

2022-04-13 18:09 UTC, imilchev approved these changes
LGTM

P.S.: I just checked and there are linting errors in the implementation. Might be better to first merge #279 and then re-base. If first this is merged and then the linting, the run on `main` will fail

2022-04-13 20:46 UTC, merged